<a href="https://colab.research.google.com/github/uiacap/UIAC_AP_MATH_4012/blob/main/Notes/AP_401_402_14_Numpy_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<div dir =rtl>
<span style="font-size:16px; font-family:xb zar">
     <strong>
numpy
</strong>
    یک کتابخانه محاسباتی برای زبان برنامه نویسی پایتون است که برای عملیات عددی و علمی استفاده می شود. این کتابخانه شامل یک سری توابع و ابزارهایی است که به کاربران امکان محاسبات عددی، جبر خطی، تبدیل فوریه، تولید اعداد تصادفی، عملیات بر روی آرایه ها و ماتریس ها و دیگر موارد را می دهد. با استفاده از NumPy، کاربر می تواند به سادگی با داده های عددی بزرگ کار کند و محاسبات پیچیده را با سرعت بالا انجام دهد. این کتابخانه یکی از کتابخانه های پایتونی محبوب است و بسیاری از کتابخانه های دیگر در زمینه هایی مانند علم داده، یادگیری ماشین و بینایی ماشینی از آن بهره می برند. 
   <br>
    برای نصب این کتابخانه از دستور زیر در محیط cmd یا powershell استفاده میشود.
       <br>

 </span>
 </div>



<code>   
    pip install jupyter
    pip install numpy
</code>

In [ ]:
import numpy as np

In [ ]:
print(help(np))

In [ ]:
print(*dir(np), sep="\n")

ALLOW_THREADS
AxisError
BUFSIZE
CLIP
ComplexWarning
DataSource
ERR_CALL
ERR_DEFAULT
ERR_IGNORE
ERR_LOG
ERR_PRINT
ERR_RAISE
ERR_WARN
FLOATING_POINT_SUPPORT
FPE_DIVIDEBYZERO
FPE_INVALID
FPE_OVERFLOW
FPE_UNDERFLOW
False_
Inf
Infinity
MAXDIMS
MAY_SHARE_BOUNDS
MAY_SHARE_EXACT
ModuleDeprecationWarning
NAN
NINF
NZERO
NaN
PINF
PZERO
RAISE
RankWarning
SHIFT_DIVIDEBYZERO
SHIFT_INVALID
SHIFT_OVERFLOW
SHIFT_UNDERFLOW
ScalarType
Tester
TooHardError
True_
UFUNC_BUFSIZE_DEFAULT
UFUNC_PYVALS_NAME
VisibleDeprecationWarning
WRAP
_CopyMode
_NoValue
_UFUNC_API
__NUMPY_SETUP__
__all__
__builtins__
__cached__
__config__
__deprecated_attrs__
__dir__
__doc__
__expired_functions__
__file__
__future_scalars__
__getattr__
__git_version__
__loader__
__name__
__package__
__path__
__spec__
__version__
_add_newdoc_ufunc
_distributor_init
_financial_names
_get_promotion_state
_globals
_mat
_no_nep50_warning
_pyinstaller_hooks_dir
_pytesttester
_set_promotion_state
_version
abs
absolute
add
add_docstring
add_newdoc
ad

<div dir =rtl>
# انواع داده ها 
</div>

## vector

In [ ]:
list_vector = [1,2,3,4,5,6]
print(list_vector)

[1, 2, 3, 4, 5, 6]


In [ ]:
np_vector = np.array(list_vector)
print(np_vector)

[1 2 3 4 5 6]


## matrix

In [ ]:
list_mtx = [[1,2,3],[4,5,6],[7,8,9]]
print(list_mtx)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [ ]:
np_mtx = np.matrix(list_mtx)
print(np_mtx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## array

In [ ]:
np_array_vec = np.array(list_vector)
print(list_vector)

[1, 2, 3, 4, 5, 6]


In [ ]:
np_array_mtx = np.array(list_mtx)
print(np_array_mtx)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


<div dir=rtl>
<span style="font-size:16px; font-family:xb zar">
     <strong>
numpy.matrix و numpy.array
</strong>
 هر دو از این نوع داده ها برای کار با آرایه های چند بعدی به کار می‌روند، اما تفاوت‌هایی با یکدیگر دارند.
<br>
     <strong>
 numpy.array
</strong>
در بیشتر موارد برای کار با داده های عددی استفاده می شود.
<br>
     <strong>
np.matrix 
</strong>
  برای کار با ماتریس ها و عملیات‌های جبری ماتریسی مانند ضرب ماتریسی استفاده میشود. 
</div>


## انتخاب مقادیر

In [ ]:
arr_1[1,2]

NameError: name 'arr_1' is not defined

In [ ]:
arr_1[1,:]

In [ ]:
arr_1[:,1]

In [ ]:
arr_1[1,1:2]

In [ ]:
arr_1[1,::2]

In [ ]:
arr_2>6

In [ ]:
arr_2[arr_2>6]

## size, shape, reshape

In [ ]:
np_array_mtx.size

In [ ]:
np_array_mtx.shape

In [ ]:
np_array_mtx.reshape((1,-1))

## dtype


<div dir =rtl>
<span style="font-size:16px; font-family:xb zar">
    یک ارایه میتواند از اعداد صحیح یا اعشاری یا مقادیر بولین تشکیل شده باشند از دستور
     <strong>
dtype
</strong>
برای نمایش نوع داده ای ارایه ها استفاده میشود. 
 </span>
</div>

### intiger

In [ ]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
print(arr_int.dtype)

int32


### float

In [ ]:
arr_float = np.array([1.0, 2.0, 3.0], dtype=np.float32)
print(arr_float.dtype)

float32


### boolean

In [ ]:
arr_bool = np.array([True, False, True])
mat_bool = np.array([[True, False], [False, True]])

print(arr_bool.dtype)
print(mat_bool.dtype)

bool
bool


### تغیر نوع داده ای آرایه ها 

In [ ]:
mat_bool.astype("float")

array([[1., 0.],
       [0., 1.]])

In [ ]:
arr_float.astype("int")

array([1, 2, 3])

# عملیات ریاضی

In [ ]:
arr_1 = np.array([[1,2,3],[4,5,6],[7,8,9]], dtype="float")
print(arr_1)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [ ]:
arr_2 = np.array([[5.6,0,15.5],[4,5,6],[7.6,  9.5, 11.4]], dtype="float")
print(arr_2)

[[ 5.6  0.  15.5]
 [ 4.   5.   6. ]
 [ 7.6  9.5 11.4]]


## جمع

In [ ]:
arr_1 + 5

array([[ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.]])

In [ ]:
arr_1 + np.array([1,2,3])

array([[ 2.,  4.,  6.],
       [ 5.,  7.,  9.],
       [ 8., 10., 12.]])

In [ ]:
arr_1 + np.array([[1],[2],[3]])

array([[ 2.,  3.,  4.],
       [ 6.,  7.,  8.],
       [10., 11., 12.]])

In [ ]:
arr_1 + arr_2

array([[ 6.6,  2. , 18.5],
       [ 8. , 10. , 12. ],
       [14.6, 17.5, 20.4]])

## تفریق

In [ ]:
arr_1 - 5

array([[-4., -3., -2.],
       [-1.,  0.,  1.],
       [ 2.,  3.,  4.]])

In [ ]:
arr_1 - np.array([1,2,3])

array([[0., 0., 0.],
       [3., 3., 3.],
       [6., 6., 6.]])

In [ ]:
arr_1 - np.array([[1],[2],[3]])

array([[0., 1., 2.],
       [2., 3., 4.],
       [4., 5., 6.]])

In [ ]:
arr_1 - arr_2

array([[ -4.6,   2. , -12.5],
       [  0. ,   0. ,   0. ],
       [ -0.6,  -1.5,  -2.4]])

## ضرب

In [ ]:
arr_1 * 5

array([[ 5., 10., 15.],
       [20., 25., 30.],
       [35., 40., 45.]])

In [ ]:
arr_1 * np.array([1,2,3])

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.],
       [ 7., 16., 27.]])

In [ ]:
arr_1 * np.array([[1],[2],[3]])

array([[ 1.,  2.,  3.],
       [ 8., 10., 12.],
       [21., 24., 27.]])

In [ ]:
arr_1 * arr_2

array([[  5.6,   0. ,  46.5],
       [ 16. ,  25. ,  36. ],
       [ 53.2,  76. , 102.6]])

In [ ]:
arr_1 @ arr_2 # arr_1.dot(arr_2)

array([[ 36.4,  38.5,  61.7],
       [ 88. ,  82. , 160.4],
       [139.6, 125.5, 259.1]])

<div dir=rtl>
<span style="font-size:16px; font-family:xb zar">
     <strong>
نکته:
</strong>
 در ضرب دو np.array استفاده از * عناصر در هم ضرب میشوند ولی در np.matrix دو ماتریس در هم ضرب میشوند.
</span>
</div>

## تقسیم

In [ ]:
arr_1 / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [ ]:
arr_1 / np.array([1,2,3])

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ],
       [7. , 4. , 3. ]])

In [ ]:
arr_1 / np.array([[1],[2],[3]])

array([[1.        , 2.        , 3.        ],
       [2.        , 2.5       , 3.        ],
       [2.33333333, 2.66666667, 3.        ]])

In [ ]:
arr_1 / arr_2

## ترانهاده

In [ ]:
arr_1.transpose() # arr_1.T

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [ ]:
arr_1.transpose()

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

# آرایه های خاص

In [ ]:
np.arange(60)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [ ]:
np.linspace(1,10,15)

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

## ماتریس 0

In [ ]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ماتریس 1

In [ ]:
np.ones((6,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.full((4,5),4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

## ماتریس همانی

In [ ]:
np.eye(4,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.eye(4,3,-1) 

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## ماتریس بالا مثلثی

In [ ]:
np.triu(arr_1)

array([[1., 2., 3.],
       [0., 5., 6.],
       [0., 0., 9.]])

## ماتریس پایین مثلثی

In [ ]:
np.tril(arr_1)

array([[1., 0., 0.],
       [4., 5., 0.],
       [7., 8., 9.]])

<span style="font-size:16px; font-family:xb zar">
     <strong>
تمرین 1: 
</strong>
    <br>
یک ماتریس با ویژگی های زیر بسازید
<ol>
  <li>اندازه ی ماتریس 4 در 5 باشد (4 سطر و 5 ستون)</li>
  <li> مقادیر ان بین 5 تا 100 باشد </li>
  <li> پس از ساخت این ماتریس انرا به ماتریس پایین مثلثی تبدیل کنید</li>
</ol>
</span>
</span<


### پاسخ

In [ ]:
np.tril(np.linspace(5,100,20).reshape((4,5)))

array([[ 5.,  0.,  0.,  0.,  0.],
       [30., 35.,  0.,  0.,  0.],
       [55., 60., 65.,  0.,  0.],
       [80., 85., 90., 95.,  0.]])

# توابع کاربردی

In [ ]:
arr_2

array([[ 5.6,  0. , 15.5],
       [ 4. ,  5. ,  6. ],
       [ 7.6,  9.5, 11.4]])

## تابع نمایی

In [ ]:
np.exp(1)

2.718281828459045

In [ ]:
np.exp(arr_2)

array([[2.70426407e+02, 1.00000000e+00, 5.38969848e+06],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.99819590e+03, 1.33597268e+04, 8.93217234e+04]])

## تابع لگاریتم

In [ ]:
np.log(arr_2)

C:\Users\MSA\AppData\Local\Temp\ipykernel_11688\987735503.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr_2)


array([[1.7227666 ,       -inf, 2.74084002],
       [1.38629436, 1.60943791, 1.79175947],
       [2.02814825, 2.2512918 , 2.43361336]])

In [ ]:
np.log2(arr_2)

C:\Users\MSA\AppData\Local\Temp\ipykernel_11688\3978570549.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr_2)


array([[2.48542683,       -inf, 3.95419631],
       [2.        , 2.32192809, 2.5849625 ],
       [2.92599942, 3.24792751, 3.51096192]])

In [ ]:
np.log10(arr_2)

C:\Users\MSA\AppData\Local\Temp\ipykernel_11688\3116882381.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(arr_2)


array([[0.74818803,       -inf, 1.1903317 ],
       [0.60205999, 0.69897   , 0.77815125],
       [0.88081359, 0.97772361, 1.05690485]])

In [ ]:
np.log(5)/np.log(6)

0.8982444017039272

## کمترین مقدار در ارایه

In [ ]:
arr_2.min()

0.0

In [ ]:
arr_2.argmin(axis=0)

array([1, 0, 1], dtype=int64)

## بیشترین مقدار در ارایه

In [ ]:
arr_2.max()

15.5

In [ ]:
arr_2.argmax()

2

## مجموع مقادیر ارایه

In [ ]:
arr_2.sum()

64.60000000000001

In [ ]:
arr_2.cumsum()

array([ 5.6,  5.6, 21.1, 25.1, 30.1, 36.1, 43.7, 53.2, 64.6])

## میانگین مقادیر ارایه

In [ ]:
arr_2.mean()

7.177777777777779

In [ ]:
arr_2.mean(axis=1)

array([7.03333333, 5.        , 9.5       ])

## انحراف مقادیر ارایه

In [ ]:
arr_2.std()

4.25435143974255

## گرد کردن اعداد

In [ ]:
arr_2.round(2)

array([[ 5.6,  0. , 15.5],
       [ 4. ,  5. ,  6. ],
       [ 7.6,  9.5, 11.4]])

In [ ]:
np.round(arr_2.mean(),3)

7.178

In [ ]:
np.ceil(arr_2)

array([[ 6.,  0., 16.],
       [ 4.,  5.,  6.],
       [ 8., 10., 12.]])

In [ ]:
np.floor(arr_2)

array([[ 5.,  0., 15.],
       [ 4.,  5.,  6.],
       [ 7.,  9., 11.]])

## برای تبدیل یک آرایه چندبعدی به یک آرایه یک بعدی 

In [ ]:
arr_1.flatten()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr_1.flatten(order="C")

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr_1.flatten(order="F")

array([1., 4., 7., 2., 5., 8., 3., 6., 9.])

## اتصال دو ارایه 

In [ ]:
arr_1.flatten(order="K")

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.vstack((arr_1,arr_2)) # np.concatenate((arr_1,arr_2), axis=0)

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [ 5.6,  0. , 15.5],
       [ 4. ,  5. ,  6. ],
       [ 7.6,  9.5, 11.4]])

In [ ]:
np.hstack((arr_1,arr_2)) # np.concatenate((arr_1,arr_2), axis=1)

array([[ 1. ,  2. ,  3. ,  5.6,  0. , 15.5],
       [ 4. ,  5. ,  6. ,  4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ,  7.6,  9.5, 11.4]])

In [ ]:
arr_3 = np.concatenate((arr_1.reshape((1,3,3)),arr_2.reshape((1,3,3))), axis=0)
arr_3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9. ]],

       [[ 5.6,  0. , 15.5],
        [ 4. ,  5. ,  6. ],
        [ 7.6,  9.5, 11.4]]])

In [ ]:
arr_3.shape

(2, 3, 3)

## توابع مثلثاتی و هایپربولیک 

In [ ]:
pi = np.pi

In [ ]:
deg = np.array([0, 30, 45, 60, 90, 180, 270, 180])

In [ ]:
rad = np.deg2rad(deg)
rad

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633,
       3.14159265, 4.71238898, 3.14159265])

In [ ]:
np.rad2deg(rad)

array([  0.,  30.,  45.,  60.,  90., 180., 270., 180.])

In [ ]:
np.round(np.sin(rad),3)

array([ 0.   ,  0.5  ,  0.707,  0.866,  1.   ,  0.   , -1.   ,  0.   ])

In [ ]:
np.round(np.cos(rad),3)

array([ 1.   ,  0.866,  0.707,  0.5  ,  0.   , -1.   , -0.   , -1.   ])

In [ ]:
np.round(np.tan(rad),3)

array([ 0.00000000e+00,  5.77000000e-01,  1.00000000e+00,  1.73200000e+00,
        1.63312394e+16, -0.00000000e+00,  5.44374645e+15, -0.00000000e+00])

In [ ]:
np.round(np.sinh(rad),3)

array([ 0.   ,  0.548,  0.869,  1.249,  2.301, 11.549, 55.654, 11.549])

In [ ]:
np.round(np.cosh(rad),3)

array([ 1.   ,  1.14 ,  1.325,  1.6  ,  2.509, 11.592, 55.663, 11.592])

In [ ]:
np.round(np.tanh(rad),3)

array([0.   , 0.48 , 0.656, 0.781, 0.917, 0.996, 1.   , 0.996])

# اعداد تصادفی

In [ ]:
np.random.seed(42)

<span style="font-size:16px; font-family:xb zar">
برخی از توزیع های اعداد تصادفی در numpy
<ul>
  <li>
توزیع یکنواخت (Uniform Distribution) 
</li>
  <li>
توزیع نرمال (Normal Distribution) 
</li>
  <li>
توزیع پوآسون (Poisson Distribution) 
</li>
  <li>
      توزیع گاما (Gamma Distribution)
</li>
  <li>
 توزیع بینومیال (Binomial  Distribution)
</li>
</ul>
</span<


## توزیع یکنواخت

![image.png](attachment:image.png)

In [ ]:
np.random.uniform(low=0.0, high=1.0, size=(10))

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

# توزیع نرمال

![image.png](attachment:image.png)

In [ ]:
arr_rnd_normal = np.random.normal(size=(5,5),loc=0.0, scale=1.0)
arr_rnd_normal

array([[-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227],
       [-1.91328024, -1.72491783, -0.56228753, -1.01283112,  0.31424733],
       [-0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 ],
       [-1.42474819, -0.54438272,  0.11092259, -1.15099358,  0.37569802],
       [-0.60063869, -0.29169375, -0.60170661,  1.85227818, -0.01349722]])

In [ ]:
arr_rnd_normal.std(), arr_rnd_normal.mean()

(0.8726954184689275, -0.35259431949304265)

## توزیع پوآسون

In [ ]:
np.random.poisson(lam=1.0, size=(2,4,3))

array([[[0, 1, 1],
        [1, 0, 5],
        [0, 0, 0],
        [0, 1, 1]],

       [[0, 1, 1],
        [2, 0, 3],
        [0, 0, 0],
        [2, 0, 0]]])

## توزیع گاما

In [ ]:
np.random.gamma(shape=1, scale=1.0, size=(2,3))

array([[0.39331421, 1.30787578, 1.01488936],
       [2.18225191, 0.63906613, 0.12737239]])

##  توزیع بینومیال

In [ ]:
np.random.binomial(n=12, p=0.3, size=4)

array([4, 5, 4, 5])

#  عملیات های جبری 

In [ ]:
arr_1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [ ]:
arr_2

array([[ 5.6,  0. , 15.5],
       [ 4. ,  5. ,  6. ],
       [ 7.6,  9.5, 11.4]])

In [ ]:
arr_3 = np.array([[4,6],[5,9]])
arr_3

array([[4, 6],
       [5, 9]])

## دترمینان ماتریس

In [ ]:
np.linalg.det(arr_3)

6.0

## ماتریس وارون

In [ ]:
arr_3_inv = np.linalg.inv(arr_3)
arr_3_inv

array([[ 1.5       , -1.        ],
       [-0.83333333,  0.66666667]])

In [ ]:
arr_3 * arr_3_inv

array([[ 6.        , -6.        ],
       [-4.16666667,  6.        ]])

In [ ]:
np.linalg.inv(arr_2)

## ماتریس شبه وارون

In [ ]:
np.linalg.pinv(arr_2)

array([[-0.00400168,  0.0125695 ,  0.02388204],
       [-0.07595293,  0.03877784,  0.07367789],
       [ 0.0659619 , -0.00454124, -0.00862835]])

##  نرم (مقدار) 

In [ ]:
np.linalg.norm(arr_2)

25.031580054003783

In [ ]:
np.linalg.norm(arr_2,ord=1)

32.9

# حل چند معادله چند مجهول

\begin{cases}  
    a_{1,1}x+b_{1,2}y+c_{1,3}z = d_1\\
    a_{2,1}x+b_{2,2}y+c_{2,3}z = d_2\\
    a_{3,1}x+b_{3,2}y+c_{3,3}z = d_3\\
  \end{cases}  


$$
\begin{bmatrix}
    a_{1,1}&b_{1,2}&c_{1,3}\\ 
    a_{2,1}&b_{2,2}&c_{2,3}\\ 
    a_{3,1}&b_{3,2}&c_{3,3}\\ 
\end{bmatrix} 
*
\begin{bmatrix}
    x \\ y \\ z
\end{bmatrix}
= 
\begin{bmatrix}
    d_1\\ 
    d_2\\ 
    d_3\\ 
\end{bmatrix} 
$$

In [ ]:
np.random.seed(42)

In [ ]:
a = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23])
np.random.shuffle(a)
a = a.reshape((3,3))
a

array([[19,  3, 13],
       [ 2, 23,  5],
       [11,  7, 17]])

In [ ]:
s = np.random.choice([1,-1],a.shape)
s

array([[ 1,  1,  1],
       [ 1, -1,  1],
       [-1, -1, -1]])

In [ ]:
A = a * s
A

array([[ 19,   3,  13],
       [  2, -23,   5],
       [-11,  -7, -17]])

In [ ]:
var = np.array([2, 3, 5, 7,11,13])
var = np.random.choice(var,3)
var

array([ 5, 13, 11])

In [ ]:
B = A @ var
B

array([ 277, -234, -333])

In [ ]:
np.linalg.solve(A,B)

array([ 5., 13., 11.])

In [ ]:
A = np.array([[1,2,3],[2,4,6],[6,8,1]])
B = np.array([6,3,7])

In [ ]:
np.linalg.solve(A,B)

# ذخیره و بارگذازی آرایه ها از فایل

In [ ]:
rnd_number = np.random.normal(size=(100,100))
rnd_number = rnd_number.round(2)

In [ ]:
np.savetxt("rnd_number.txt",rnd_number,fmt='%.2e')

In [ ]:
np.loadtxt("rnd_number.txt",dtype="float")
# np.loadtxt("mtx2.txt",dtype="float",delimiter=",")

array([[-0.58, -0.53, -0.57, ...,  1.4 , -0.02, -1.67],
       [-1.07, -0.99,  0.1 , ...,  1.07, -0.96,  1.38],
       [ 0.91, -0.6 ,  0.3 , ...,  1.16,  1.55, -0.44],
       ...,
       [ 0.28, -0.3 , -1.34, ..., -1.1 ,  1.56,  0.25],
       [ 0.4 ,  0.44, -1.2 , ..., -0.99, -0.69, -1.27],
       [ 0.15,  0.81, -0.07, ...,  0.16,  0.8 ,  1.19]])

In [ ]:
np.savetxt("rnd_number.txt",rnd_number,fmt='%.2e')

In [ ]:
with open("rnd_number.npy","wb") as f:
    np.save(f,rnd_number)

In [ ]:
with open("rnd_number.npy","rb") as f:
    aa = np.load(f)